name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-filesystem:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup fbox
      run: |
        mkdir -p www
        nohup uvicorn fbox.main:app &
    - name: Test with pytest
      run: |
        pytest

  test-s3remote:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: test
      STORAGE_ENGINE: "s3remote"
      S3_ENDPOINT_URL: "http://127.0.0.1:9000/"
      S3_ACCESS_KEY: "minioadmin"
      S3_SECRET_KEY: "minioadmin"
    services:
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ROOT_USER: "minioadmin"
          MINIO_ROOT_PASSWORD: "minioadmin"
        ports:
          - 9000:9000
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup fbox
      run: |
        mkdir -p www
        nohup uvicorn fbox.main:app &
    - name: Test with pytest
      run: |
        pytest
